import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import { BiMessageSquareDots } from "react-icons/bi";
export default function Home() {
    return (
        <>
            <Head>
                <title>RootNode</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Sidebar />
            <main className="flex min-h-screen mx-auto  bg-rn-black text-rn-white ">
                <div className="xl:ml-[370px] xl:min-w-[576px] sm:ml-[73px] flex-grow max-w-xl">
                    <div className="flex py-2 px-3 sticky top-0 z-50 bg-rn-black">
                        <h2 className="text-lg sm:text-xl font-bold cursor-pointer">
                            HOME SCREEN
                        </h2>
                        <div className="hoverEffect flex items-center justify-center px-0 ml-auto w-9 h-9">
                            <BiMessageSquareDots className="h-9 w-9 hoverEffect p-2 hover:text-sky-500 hover:bg-sky-100" />
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
}
